"""Initial command journal orders and trades"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commands',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('timestamp_us', sa.BigInteger(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('response', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('order_type', sa.String(length=6), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=True),
    sa.Column('original_quantity', sa.BigInteger(), nullable=False),
    sa.Column('remaining_quantity', sa.BigInteger(), nullable=False),
    sa.Column('executed_quantity', sa.BigInteger(), nullable=False),
    sa.Column('quantity_adjustment', sa.BigInteger(), nullable=False),
    sa.Column('creation_sequence', sa.BigInteger(), nullable=False),
    sa.Column('priority_sequence', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.CheckConstraint("(order_type = 'LIMIT' AND price IS NOT NULL AND price > 0) OR (order_type = 'MARKET' AND price IS NULL)"),
    sa.CheckConstraint("order_type IN ('LIMIT', 'MARKET')"),
    sa.CheckConstraint("side IN ('BUY', 'SELL')"),
    sa.CheckConstraint("status IN ('NEW', 'PARTIALLY_FILLED', 'FILLED', 'CANCELLED')"),
    sa.CheckConstraint('original_quantity > 0 AND remaining_quantity >= 0 AND executed_quantity >= 0'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('maker_order_id', sa.BigInteger(), nullable=False),
    sa.Column('taker_order_id', sa.BigInteger(), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('execution_sequence', sa.BigInteger(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('price > 0 AND quantity > 0 AND maker_order_id <> taker_order_id'),
    sa.ForeignKeyConstraint(['maker_order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['taker_order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('execution_sequence')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trades')
    op.drop_table('orders')
    op.drop_table('commands')
    # ### end Alembic commands ###
